app = "ming-blog"
primary_region = "nrt"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[[mounts]]
  source = "blog_data"
  destination = "/data"
